package com.haoding.demo.po;

public class StockInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_id
     *
     * @mbggenerated
     */
    private String stockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_name
     *
     * @mbggenerated
     */
    private String stockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.issuance_time
     *
     * @mbggenerated
     */
    private String issuanceTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.closing_price_y
     *
     * @mbggenerated
     */
    private Double closingPriceY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.opening_price_t
     *
     * @mbggenerated
     */
    private Double openingPriceT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.closing_price_t
     *
     * @mbggenerated
     */
    private Double closingPriceT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.stock_type
     *
     * @mbggenerated
     */
    private String stockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_info.block
     *
     * @mbggenerated
     */
    private String block;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_info
     *
     * @mbggenerated
     */
    public StockInfo(String stockId, String stockName, String issuanceTime, Double closingPriceY, Double openingPriceT, Double closingPriceT, String stockType, String block) {
        this.stockId = stockId;
        this.stockName = stockName;
        this.issuanceTime = issuanceTime;
        this.closingPriceY = closingPriceY;
        this.openingPriceT = openingPriceT;
        this.closingPriceT = closingPriceT;
        this.stockType = stockType;
        this.block = block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_id
     *
     * @return the value of stock_info.stock_id
     *
     * @mbggenerated
     */
    public String getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_name
     *
     * @return the value of stock_info.stock_name
     *
     * @mbggenerated
     */
    public String getStockName() {
        return stockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.issuance_time
     *
     * @return the value of stock_info.issuance_time
     *
     * @mbggenerated
     */
    public String getIssuanceTime() {
        return issuanceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.closing_price_y
     *
     * @return the value of stock_info.closing_price_y
     *
     * @mbggenerated
     */
    public Double getClosingPriceY() {
        return closingPriceY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.opening_price_t
     *
     * @return the value of stock_info.opening_price_t
     *
     * @mbggenerated
     */
    public Double getOpeningPriceT() {
        return openingPriceT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.closing_price_t
     *
     * @return the value of stock_info.closing_price_t
     *
     * @mbggenerated
     */
    public Double getClosingPriceT() {
        return closingPriceT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.stock_type
     *
     * @return the value of stock_info.stock_type
     *
     * @mbggenerated
     */
    public String getStockType() {
        return stockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_info.block
     *
     * @return the value of stock_info.block
     *
     * @mbggenerated
     */
    public String getBlock() {
        return block;
    }
}